import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom';
import './styles.css';

import { BlogProvider, useBlog, Writer } from './blog';
import type { Post as BlogPost } from './blog';

function Layout({children}:{children:React.ReactNode}) { return <><header><Link className="brand" to="/">a little corner</Link><nav><Link to="/">Home</Link><Link to="/about">About</Link><Link to="/blog">Blog</Link><Link to="/contact">Contact</Link></nav></header><main>{children}</main><footer>Made for little joys, honest stories & hopeful days. 🍂 <Link className="writer-link" to="/writer">Writer login</Link></footer></> }
function Home(){const {posts} = useBlog(); return <><section className="hero"><div><p className="eyebrow">WELCOME IN</p><h1>A soft place for everyday life.</h1><p className="lead">Stories, little joys, coffee moments, and reminders that even ordinary days can hold something beautiful.</p><Link className="button" to="/blog">Read the latest story →</Link></div><div className="hero-card"><span>☕️</span><p>Take a breath.<br/>Stay a while.</p></div></section><section className="intro"><p className="eyebrow">FROM THE PORCH</p><h2>A little corner of the internet made to feel happy.</h2><p>Nothing here has to be perfect. Just real life, encouragement, and the small things that make a day feel a little brighter.</p></section>{posts.length > 0 && <section className="latest"><div><p className="eyebrow">LATEST STORY</p><h2>{posts[0].title}</h2><p>{posts[0].summary}</p></div><Link to={'/blog/'+posts[0].slug}>Keep reading →</Link></section>}</>}
function Blog(){const {posts} = useBlog(); return <><section className="page-head"><p className="eyebrow">THE BLOG</p><h1>Stories from everyday life.</h1><p>Little reflections, encouragement, and the moments worth slowing down for.</p></section>{!posts.length && <p>More little stories are on their way. Come back soon.</p>}<div className="post-list">{posts.map(p=><article className="post-card" key={p.slug}><p className="date">{p.date}</p><h2>{p.title}</h2><p>{p.summary}</p><Link to={'/blog/'+p.slug}>Read story →</Link></article>)}</div></>}
function Post({post}:{post:BlogPost}){return <article className="single"><p className="date">{post.date}</p><h1>{post.title}</h1><p className="lead">{post.summary}</p>{post.body.split('\n\n').map((x,i)=><p className="story-paragraph" key={i}>{x}</p>)}<Link to="/blog">← Back to stories</Link></article>}
function PostPage(){const {slug} = useParams(); const {posts} = useBlog(); const post = posts.find(p => p.slug === slug); return post ? <Post post={post}/> : <section className="single"><h1>Story not found.</h1><Link to="/blog">Back to stories</Link></section>}
function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<section className="single"><p className="eyebrow">ABOUT</p><h1>Come on in.</h1><p className="lead">This is a little corner for sharing everyday life, finding the good stuff, and leaving a bit of encouragement behind.</p><p>It’s intentionally simple. No pressure to have all the answers. Just a place to tell stories, notice small joys, and maybe make somebody smile.</p></section>}/><Route path="/blog" element={<Blog/>}/><Route path="/blog/:slug" element={<PostPage/>}/><Route path="/writer" element={<Writer/>}/><Route path="/contact" element={<section className="single"><p className="eyebrow">CONTACT</p><h1>Say hello.</h1><p className="lead">This page is just a placeholder for now. When the time is right, it can become whatever feels natural.</p></section>}/></Routes></Layout>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><BlogProvider><App/></BlogProvider></BrowserRouter></React.StrictMode>);
